<?php
namespace application\forms\book;

use application\entities\author\Book;
use application\forms\BaseForm;

use yii\base\Model;
use yii\helpers\ArrayHelper;

/**
 * Signup form
 */
class BookForm extends BaseForm
{
    public $title;
    public $author_id;
    public $date_at;

    private $_model;

    public function __construct(Book $model = null,array $config = [])
    {
        $this->_model = $model;
        parent::__construct($config);

    }/**/

    public function init()
    {
        parent::init();
        if($this->_model){
            $this->fillFromModel($this->_model);
        }
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title','author_id','date_at'],'required'],
            ['author_id','integer'],
            [['title','date_at'],'string'],
            ['date_at','date','format'=>'dd.MM.yyyy HH:mm:ss'],
        ];
    }/**/

    public function attributeLabels()
    {
      return $this->_model ? $this->_model->attributeLabels() : [];

    }


    public function __get($name)
    {
        if($this->_model){
            return $this->_model->$name;
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }/**/

    public function afterValidate()
    {

       parent::afterValidate();
       $this->setDateForDb();

    }/**/

    public function setDateForDb(){
        $this->date_at = date("Y-m-d H:i:s",strtotime($this->date_at));
    }/**/


}
